# Generated by Django 3.1 on 2020-10-06 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=50, null=True)),
                ('manufacture_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('description', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('warehouse', models.CharField(choices=[('store', 'store'), ('upstairs', 'upstairs'), ('warehouse', 'warehouse')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50, null=True)),
                ('stock', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('med_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.medicine')),
            ],
        ),
    ]
